# RAPP API Travis Continuous Integration Configuration File
# Author: Maria Ramos <m.ramos@ortelio.co.uk>
# 
language: g++ 
sudo: required
dist: trusty
compiler:
    - g++
os:
    - linux

branches:
    only:
    - cpp_dev

branches:
    except:
    - master
    - cpp
    - api_stable
    - cpp-wut
    - devel
    - js
    - ortelio_devel_merge
    - ortelio
    - /^wut-*$/
    - /^wut_*$/

before_install: 
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -y
    - sudo apt-get install gcc-4.9 g++-4.9 libboost1.55-all-dev cmake -y
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 10
    - sudo update-alternatives --set g++ /usr/bin/g++-4.9

install: true

script:
    - mkdir -p cpp/build
    - cd cpp/build
    - cmake .. -DBUILD_TESTS=ON 
    - make
    - sudo make install
    - make test
