services:
  list:
    - available_services
    - speech_detection_sphinx4
    - speech_detection_google
    - qr_detection
    - face_detection
    - set_noise_profile
    - ontology_subclasses_of
    - ontology_superclasses_of
    - ontology_is_subsuperclass_of
    - detect_objects
    - cognitive_test_chooser
    - record_cognitive_test_performance
    - text_to_speech
